#!/bin/bash

set -x

date

echo "into launch_allvars_hrrr"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

module load wgrib2/2.0.8_wmo
mkdir -p /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
cd /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
echo $COMrrfs

if [ $domset = 'conus' ]; then
  dom='conus'
elif [ $domset = 'oconus' ]; then
  dom='ak'
  HRRR_AK_DIR=/lfs/h1/ops/prod/com/hrrr/v4.1/hrrr.${PDY}/alaska
  gridspecs="nps:210.0:60.0 181.429:1649:2976.0 40.530:1105:2976.0"

  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2
  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2
  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2

  if [ -s hrrr.t${cyc}z.wrfprsf00.ak.grib2 ]; then
    echo "Found f00 file, wgrib2 interpolation not needed"
  else
    wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf00.ak.grib2 \
      -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
      -new_grid_interpolation neighbor \
      -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
      -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf00.ak.grib2
  fi
fi

if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2" ] ; then
    cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -match ave -not MASSDEN -grib rrfs_${dom}_piece1_f0${fhr}.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -not ave -grib rrfs_${dom}_piece2_f0${fhr}.grib2
    cat rrfs_${dom}_piece1_f0${fhr}.grib2 rrfs_${dom}_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2
fi

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}

python ${HOMEDIR}/scripts/plot_allvars_hrrr.py $CDATE $fhr $USER $domset

date

exit
