#!/bin/bash

set -x

date

if [[ "${cyc}" == "06" ]] || [[ "${cyc}" == "18" ]]; then
  domset='alaska_pr'
else
  domset='conus_hawaii'
fi

echo "into launch_allvars_hiresw"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/2panel_hiresw/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/2panel_hiresw/${PDY}/${cyc}

if [ $member = 'arw' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_arw.py $CDATE $fhr $USER $domset
elif [ $member = 'arw2' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_arw2.py $CDATE $fhr $USER $domset
elif [ $member = 'fv3' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_fv3.py $CDATE $fhr $USER $domset
fi

date

exit
