#!/bin/bash


date

echo "into launch_dpt2m_plot"
module load prod_util/2.0.13

set -x
VDATE=$($NDATE +$fhr $CDATE)
PDY=`echo $CDATE | cut -c1-8`
cyc=`echo $CDATE | cut -c9-10`
set +x

module load wgrib2/2.0.8_wmo
mkdir -p /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
cd /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
echo $COMrrfs
for dom in conus ak; do
    if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2" ] ; then
        cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2
        wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -match ave -not MASSDEN -grib rrfs_${dom}_piece1_f0${fhr}.grib2
        wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -not ave -grib rrfs_${dom}_piece2_f0${fhr}.grib2
        cat rrfs_${dom}_piece1_f0${fhr}.grib2 rrfs_${dom}_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2
    fi
done

for dom in pr hi; do
    if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}.grib2" ] ; then
        cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}.grib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}_bad.grib2
        wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}_bad.grib2 -match ave -not MASSDEN -grib rrfs_${dom}_piece1_f0${fhr}.grib2
        wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}_bad.grib2 -not ave -grib rrfs_${dom}_piece2_f0${fhr}.grib2
        cat rrfs_${dom}_piece1_f0${fhr}.grib2 rrfs_${dom}_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.${dom}.grib2
    fi
done

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/4panel_dpt2m/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/4panel_dpt2m/${PDY}/${cyc}

echo "Running plots (grib2io env)"
module reset
module load prod_envir/2.0.6
module load intel/19.1.3.304
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:${HOMEDIR}/modulefiles"
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
module load imagemagick/7.0.8-7

python ${HOMEDIR}/scripts/plot_dpt2m_verif.py $VDATE $CDATE $fhr $USER

date

exit
