#!/bin/bash

set -x

date

if [[ "${cyc}" == "06" ]] || [[ "${cyc}" == "18" ]]; then
  domset='alaska_pr'
else
  domset='conus_hawaii'
fi

echo "into launch_allvars_hiresw"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

module load wgrib2/2.0.8_wmo
mkdir -p /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
cd /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
echo $COMrrfs

if [ $domset = 'conus_hawaii' ]; then
  if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus.grib2" ]; then
    cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus.grib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus_bad.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus_bad.grib2 -match ave -not MASSDEN -grib rrfs_conus_piece1_f0${fhr}.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus_bad.grib2 -not ave -grib rrfs_conus_piece2_f0${fhr}.grib2
    cat rrfs_conus_piece1_f0${fhr}.grib2 rrfs_conus_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.3km.f0${fhr}.conus.grib2
  fi

  if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi.grib2" ]; then
    cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi.grib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi_bad.grib2
    wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi_bad.grib2 -match ave -not MASSDEN -grib rrfs_hi_piece1_f0${fhr}.grib2
    wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi_bad.grib2 -not ave -grib rrfs_hi_piece2_f0${fhr}.grib2
    cat rrfs_hi_piece1_f0${fhr}.grib2 rrfs_hi_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.hi.grib2
  fi

elif [ $domset = 'alaska_pr' ]; then
  if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak.grib2" ]; then
    cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak.grib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak_bad.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak_bad.grib2 -match ave -not MASSDEN -grib rrfs_ak_piece1_f0${fhr}.grib2
    wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak_bad.grib2 -not ave -grib rrfs_ak_piece2_f0${fhr}.grib2
    cat rrfs_ak_piece1_f0${fhr}.grib2 rrfs_ak_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.3km.f0${fhr}.ak.grib2
  fi

  if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr.grib2" ]; then
    cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr.grib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr_bad.grib2
    wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr_bad.grib2 -match ave -not MASSDEN -grib rrfs_pr_piece1_f0${fhr}.grib2
    wgrib2 rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr_bad.grib2 -not ave -grib rrfs_pr_piece2_f0${fhr}.grib2
    cat rrfs_pr_piece1_f0${fhr}.grib2 rrfs_pr_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.2p5km.f0${fhr}.pr.grib2
  fi

fi

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/2panel_hiresw/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/2panel_hiresw/${PDY}/${cyc}

if [ $member = 'arw' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_arw.py $CDATE $fhr $USER $domset
elif [ $member = 'arw2' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_arw2.py $CDATE $fhr $USER $domset
elif [ $member = 'fv3' ]; then
  python ${HOMEDIR}/scripts/plot_allvars_hiresw_fv3.py $CDATE $fhr $USER $domset
fi

date

exit
