#!/bin/bash

set -x

date

#domset='conus'

echo "into launch_allvars_nam"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}

python ${HOMEDIR}/scripts/plot_allvars_nam.py $CDATE $fhr $USER $domset

date

exit
