#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023082400
#PDY=20230824
#cyc=00
#fhr=24

echo "into launch_allvars_namerica"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/namerica/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/namerica/${PDY}/${cyc}

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/scripts/plot_allvars_namerica.py $CDATE $fhr

date

exit
