#!/bin/bash


date

echo "into launch_refc_prep"
module load prod_util/2.0.13

set -x
VDATE=$($NDATE +$fhr $CDATE)
PDY=`echo $CDATE | cut -c1-8`
cyc=`echo $CDATE | cut -c9-10`
set +x

module load wgrib2/2.0.8_wmo
mkdir -p /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
cd /lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}
echo $COMrrfs
for dom in conus ak; do
    if ! [ -f "/lfs/h2/emc/ptmp/${USER}/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2" ] ; then
        cp ${COMrrfs}/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2
        wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -match ave -not MASSDEN -grib rrfs_${dom}_piece1_f0${fhr}.grib2
        wgrib2 rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}_bad.grib2 -not ave -grib rrfs_${dom}_piece2_f0${fhr}.grib2
        cat rrfs_${dom}_piece1_f0${fhr}.grib2 rrfs_${dom}_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.3km.f0${fhr}.${dom}.grib2
    fi
done

echo "Running METplus prep (METplus env)"
module reset
module load prod_envir/2.0.6
module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304
export HPC_OPT=/apps/ops/para/libs
module use /apps/dev/modulefiles
module load PrgEnv-intel/8.3.3
module load intel/19.1.3.304
module load ve/evs/2.0
module load cray-mpich/8.1.19
module load cray-pals/1.2.2
module load cfp/2.0.4
module load libjpeg/9c
module load libpng/1.6.37
module load zlib/1.2.11
module load jasper/2.0.25
module load udunits/2.2.28
module load gsl/2.7
module load netcdf/4.7.4
module load nco/5.0.6
module load prod_util/2.0.14
module load cdo/1.9.8
module load grib_util/1.2.4
module load wgrib2/2.0.8
module load met/12.0.0-rc1
module load metplus/6.0.0-rc1
export PYTHONPATH="${HOMEDIR}/modulefiles:${PYTHONPATH}"

python ${HOMEDIR}/scripts/prep_refc_metplus.py $VDATE $CDATE $fhr

date

exit
