#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023082400
#PDY=20230824
#cyc=00
#fhr=24

echo "into launch_allvars_namerica"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/PyGSI"

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/namerica/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/namerica/${PDY}/${cyc}

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/plot_allvars_namerica.py $CDATE $fhr

date

exit
