#!/bin/bash

set -x

date

echo "into launch_allvars_hrrr"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/ptmp/${USER}/hrrr/hrrr.${PDY}/${cyc}/alaska
cd /lfs/h2/emc/ptmp/${USER}/hrrr/hrrr.${PDY}/${cyc}/alaska
echo $COMrrfs

if [ $domset = 'conus' ]; then
  dom='conus'
elif [ $domset = 'oconus' ]; then
  dom='ak'
  HRRR_AK_DIR=/lfs/h1/ops/prod/com/hrrr/v4.1/hrrr.${PDY}/alaska
  gridspecs="nps:210.0:60.0 181.429:1649:2976.0 40.530:1105:2976.0"

  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2
  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2
  wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2 \
    -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
    -new_grid_interpolation neighbor \
    -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
    -new_grid ${gridspecs} hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2

  if [ -s hrrr.t${cyc}z.wrfprsf00.ak.grib2 ]; then
    echo "Found f00 file, wgrib2 interpolation not needed"
  else
    wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf00.ak.grib2 \
      -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
      -new_grid_interpolation neighbor \
      -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
      -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf00.ak.grib2
  fi
fi

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}

python ${HOMEDIR}/scripts/plot_allvars_hrrr.py $CDATE $fhr $USER $domset

date

exit
