#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023082200
#PDY=20230822
#cyc=00
#dom='puerto_rico'

echo "into launch_qpfsnowfall_nam"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}

python ${HOMEDIR}/scripts/plot_qpfsnowfall_nam.py $CDATE $dom

date

exit
