#!/bin/bash


date

echo "into launch_slp_plot"
module load prod_util/2.0.13

set -x
VDATE=$($NDATE +$fhr $CDATE)
PDY=`echo $CDATE | cut -c1-8`
cyc=`echo $CDATE | cut -c9-10`
set +x

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/4panel_slp/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/4panel_slp/${PDY}/${cyc}

echo "Running plots (grib2io env)"
module reset
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

python ${HOMEDIR}/scripts/plot_slp_verif.py $VDATE $CDATE $fhr $USER

date

exit
