#!/bin/bash

set -x

date

echo "into launch_qpfsnowfall_firewx"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}

latlon=/lfs/h1/ops/prod/com/nam/v4.2/input/nam_firewx_loc
cen_lat=`grep ${cyc}z $latlon | awk '{print $2}'`
cen_lon=`grep ${cyc}z $latlon | awk '{print $3}'`

python ${HOMEDIR}/scripts/plot_qpfsnowfall_firewx.py $CDATE $cen_lat $cen_lon

date

exit
