#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023092600
#PDY=`echo $CDATE | cut -c1-8`
#cyc=`echo $CDATE | cut -c9-10`
exp=RRFS_A

echo 'into launch_histograms'
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/rrfs_graphics/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/damonitor
mkdir -p /lfs/h2/emc/stmp/${USER}/damonitor/$PDY
mkdir -p /lfs/h2/emc/stmp/${USER}/damonitor/$PDY/$cyc

mkdir -p /lfs/h2/emc/stmp/${USER}/cnvstat/${CDATE}
cd /lfs/h2/emc/stmp/${USER}/cnvstat/${CDATE}

# Retrieve diag_conv files
cp ${COMrrfs}/rrfs.${PDY}/${cyc}/diag_conv_*${CDATE}.nc4.gz .
gunzip diag*gz

# Modify yaml files for the date of interest
cp ${HOMErrfs}/parm/rrfs_o-f_template.yaml .
sed 's/CDATE/'${CDATE}'/g' rrfs_o-f_template.yaml > tmpfile ; mv tmpfile rrfs_o-f.yaml

cp ${HOMErrfs}/parm/rrfs_o-a_template.yaml .
sed 's/CDATE/'${CDATE}'/g' rrfs_o-a_template.yaml > tmpfile ; mv tmpfile rrfs_o-a.yaml


cd /lfs/h2/emc/stmp/${USER}/damonitor/$PDY/$cyc

# Run Python script
python ${HOMErrfs}/scripts/plot_histograms.py -y /lfs/h2/emc/stmp/${USER}/cnvstat/${CDATE}/rrfs_o-f.yaml -y2 /lfs/h2/emc/stmp/${USER}/cnvstat/${CDATE}/rrfs_o-a.yaml -e ${exp} -o ./

convert ${exp}_conv_ps_o-f_metar_assimilated.png ${exp}_conv_ps_o-a_metar_assimilated.png +append ${exp}_conv_ps_metar_assimilated.png
convert ${exp}_conv_ps_o-f_mesonet_assimilated.png ${exp}_conv_ps_o-a_mesonet_assimilated.png +append ${exp}_conv_ps_mesonet_assimilated.png

convert ${exp}_conv_t_o-f_metar_assimilated.png ${exp}_conv_t_o-a_metar_assimilated.png +append ${exp}_conv_t_metar_assimilated.png
convert ${exp}_conv_t_o-f_mesonet_assimilated.png ${exp}_conv_t_o-a_mesonet_assimilated.png +append ${exp}_conv_t_mesonet_assimilated.png

convert ${exp}_conv_q_o-f_metar_assimilated.png ${exp}_conv_q_o-a_metar_assimilated.png +append ${exp}_conv_q_metar_assimilated.png
convert ${exp}_conv_q_o-f_mesonet_assimilated.png ${exp}_conv_q_o-a_mesonet_assimilated.png +append ${exp}_conv_q_mesonet_assimilated.png

convert ${exp}_conv_u_o-f_metar_assimilated.png ${exp}_conv_u_o-a_metar_assimilated.png +append ${exp}_conv_u_metar_assimilated.png
convert ${exp}_conv_u_o-f_mesonet_assimilated.png ${exp}_conv_u_o-a_mesonet_assimilated.png +append ${exp}_conv_u_mesonet_assimilated.png

convert ${exp}_conv_v_o-f_metar_assimilated.png ${exp}_conv_v_o-a_metar_assimilated.png +append ${exp}_conv_v_metar_assimilated.png
convert ${exp}_conv_v_o-f_mesonet_assimilated.png ${exp}_conv_v_o-a_mesonet_assimilated.png +append ${exp}_conv_v_mesonet_assimilated.png

rm -f ${exp}*o-f*.png
rm -f ${exp}*o-a*.png

date

exit
