#!/bin/bash


date

echo "into launch_refc_plot"
module load prod_util/2.0.13

set -x
VDATE=$($NDATE +$fhr $CDATE)
PDY=`echo $CDATE | cut -c1-8`
cyc=`echo $CDATE | cut -c9-10`
set +x

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/4panel_refc/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/4panel_refc/${PDY}/${cyc}

echo "Running plots (grib2io env)"
module reset
module load prod_envir/2.0.6
module load intel/19.1.3.304
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:${HOMEDIR}/modulefiles"
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
module load imagemagick/7.0.8-7

python ${HOMEDIR}/scripts/plot_refc_verif.py $VDATE $CDATE $fhr $USER

date

exit
