#!/bin/bash

set -x

date

domset='oconus'

echo "into launch_allvars_nam"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/rrfs_graphics/modulefiles"
module load imagemagick/7.0.8-7

module load wgrib2/2.0.8_wmo
mkdir -p /lfs/h2/emc/ptmp/Benjamin.Blake/rrfs/na/prod/rrfs.${PDY}/${cyc}
cd /lfs/h2/emc/ptmp/Benjamin.Blake/rrfs/na/prod/rrfs.${PDY}/${cyc}

cp /lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.f0${fhr}.ak.grib2 rrfs.t${cyc}z.prslev.f0${fhr}.ak_bad.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.ak_bad.grib2 -match ave -not MASSDEN -grib rrfs_ak_piece1_f0${fhr}.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.ak_bad.grib2 -not ave -grib rrfs_ak_piece2_f0${fhr}.grib2
cat rrfs_ak_piece1_f0${fhr}.grib2 rrfs_ak_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.f0${fhr}.ak.grib2

cp /lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.f0${fhr}.hi.grib2 rrfs.t${cyc}z.prslev.f0${fhr}.hi_bad.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.hi_bad.grib2 -match ave -not MASSDEN -grib rrfs_hi_piece1_f0${fhr}.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.hi_bad.grib2 -not ave -grib rrfs_hi_piece2_f0${fhr}.grib2
cat rrfs_hi_piece1_f0${fhr}.grib2 rrfs_hi_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.f0${fhr}.hi.grib2

cp /lfs/h2/emc/ptmp/emc.lam/rrfs/na/prod/rrfs.${PDY}/${cyc}/rrfs.t${cyc}z.prslev.f0${fhr}.pr.grib2 rrfs.t${cyc}z.prslev.f0${fhr}.pr_bad.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.pr_bad.grib2 -match ave -not MASSDEN -grib rrfs_pr_piece1_f0${fhr}.grib2
wgrib2 rrfs.t${cyc}z.prslev.f0${fhr}.pr_bad.grib2 -not ave -grib rrfs_pr_piece2_f0${fhr}.grib2
cat rrfs_pr_piece1_f0${fhr}.grib2 rrfs_pr_piece2_f0${fhr}.grib2 > rrfs.t${cyc}z.prslev.f0${fhr}.pr.grib2

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/scripts/plot_allvars_nam.py $CDATE $fhr $domset

date

exit
