#!/bin/bash

set -x

date

echo "into launch_allvars_nam"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/PyGSI"

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_nam/${PDY}/${cyc}

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/scripts/plot_allvars_nam.py $CDATE $fhr

date

exit
