#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023082200
#PDY=20230822
#cyc=00
#fhr=24

HRRR_AK_DIR=/lfs/h1/ops/prod/com/hrrr/v4.1/hrrr.${PDY}/alaska

echo "into launch_allvars_hrrr"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/PyGSI"

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/3panel_hrrr/${PDY}/${cyc}

module load wgrib2/2.0.8_wmo
gridspecs="nps:210.0:60.0 181.429:1649:2976.0 40.530:1105:2976.0"

wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2 \
  -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
  -new_grid_interpolation neighbor \
  -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
  -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf${fhr}.ak.grib2
wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2 \
  -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
  -new_grid_interpolation neighbor \
  -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
  -new_grid ${gridspecs} hrrr.t${cyc}z.wrfnatf${fhr}.ak.grib2
wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2 \
  -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
  -new_grid_interpolation neighbor \
  -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
  -new_grid ${gridspecs} hrrr.t${cyc}z.wrfsfcf${fhr}.ak.grib2
wgrib2 ${HRRR_AK_DIR}/hrrr.t${cyc}z.wrfprsf00.ak.grib2 \
  -set_bitmap 1 -set_grib_type c3 -new_grid_winds grid \
  -new_grid_interpolation neighbor \
  -if ":(WEASD|APCP|NCPCP|ACPCP|SNOD):" -new_grid_interpolation budget -fi \
  -new_grid ${gridspecs} hrrr.t${cyc}z.wrfprsf00.ak.grib2


python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/plot_allvars_hrrr.py $CDATE $fhr

date

exit
