#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023082400
#PDY=20230824
#cyc=00
#fhr=24

echo "into launch_allvars_firewx"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/rrfs_graphics/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}

#latlon=/lfs/h2/emc/ptmp/emc.lam/para/com/rrfsfw/v1.0.0/rrfsfw.${PDY}/${cyc}/rrfsfw.t${cyc}z.firewxnest_center_latlon
#cen_lat=`cat $latlon | cut -c1-4`
#cen_lon=`cat $latlon | cut -c6-11`

latlon=/lfs/h1/ops/prod/com/nam/v4.2/input/nam_firewx_loc
cen_lat=`grep ${cyc}z $latlon | awk '{print $2}'`
cen_lon=`grep ${cyc}z $latlon | awk '{print $3}'`

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/scripts/plot_allvars_firewx.py $CDATE $fhr $cen_lat $cen_lon

date

exit
