#!/bin/bash

set -x

date

#USER=Benjamin.Blake
#CDATE=2023091906
#PDY=20230919
#cyc=06

echo "into launchtest"
module load python/3.8.6
module use /lfs/h1/mdl/nbm/save/apps/modulefiles
module load python-modules/3.8.6
module load proj/7.1.0
module load geos/3.8.1
module load libjpeg-turbo/2.1.0
export PYTHONPATH="${PYTHONPATH}:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/python:/lfs/h2/emc/lam/noscrub/Benjamin.Blake/rrfs_graphics/modulefiles"
module load imagemagick/7.0.8-7

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/firewx/${PDY}/${cyc}

latlon=/lfs/h2/emc/ptmp/emc.lam/para/com/rrfsfw/v1.0.0/rrfsfw.${PDY}/${cyc}/rrfsfw.t${cyc}z.firewxnest_center_latlon
cen_lat=`cat $latlon | cut -c1-4`
cen_lon=`cat $latlon | cut -c6-11`

python /lfs/h2/emc/lam/noscrub/${USER}/rrfs_graphics/scripts/plot_qpf_firewx.py $CDATE $cen_lat $cen_lon

date

exit
