#!/bin/bash


date

#USER=Benjamin.Blake
#CDATE=2024080512	# This is for the valid ending time of the 24-hr period
#fhr=24

echo "into launch_qpf_verif"
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7
module load prod_util/2.0.13

#module load prod_util	# for NDATE
set -x
VDATE=$($NDATE +$fhr $CDATE)
PDY=`echo $CDATE | cut -c1-8`
cyc=`echo $CDATE | cut -c9-10`
fhrm24=$((10#$fhr - 24))
if [ "$fhrm24" -lt 0 ]; then
    echo "Quitting because for 24-h accumulation windows, we need the starting fhr to be >= 00"
    exit 1
fi
printf -v fhrm24_padded "%02d" "$fhrm24"
set +x

mkdir -p /lfs/h2/emc/stmp/${USER}
mkdir -p /lfs/h2/emc/stmp/${USER}/4panel_qpf/${PDY}/${cyc}
cd /lfs/h2/emc/stmp/${USER}/4panel_qpf/${PDY}/${cyc}

# LOAD ENV 1
echo "Running METplus prep (METplus env)"
module reset
module load prod_envir/2.0.6
module use /apps/ops/para/libs/modulefiles/compiler/intel/19.1.3.304
export HPC_OPT=/apps/ops/para/libs
module use /apps/dev/modulefiles
module load PrgEnv-intel/8.3.3
module load intel/19.1.3.304
module load ve/evs/2.0
module load cray-mpich/8.1.19
module load cray-pals/1.2.2
module load cfp/2.0.4
module load libjpeg/9c
module load libpng/1.6.37
module load zlib/1.2.11
module load jasper/2.0.25
module load udunits/2.2.28
module load gsl/2.7
module load netcdf/4.7.4
module load nco/5.0.6
module load prod_util/2.0.14
module load cdo/1.9.8
module load grib_util/1.2.4
module load wgrib2/2.0.8
module load met/12.0.0-rc1
module load metplus/6.0.0-rc1
export PYTHONPATH="${HOMEDIR}/modulefiles:${PYTHONPATH}"

python ${HOMEDIR}/scripts/prep_qpf_metplus.py $VDATE $CDATE $fhr

# LOAD ENV 2
echo "Running plots (grib2io env)"
module reset
source /u/benjamin.blake/.bashrc
export PYTHONPATH="${PYTHONPATH}:${HOMEDIR}/modulefiles"
module load imagemagick/7.0.8-7

python ${HOMEDIR}/scripts/plot_qpf_verif.py $VDATE $CDATE $fhr

date

exit
